FROM node:20-alpine

WORKDIR /app

COPY frontend/package.json ./

RUN npm install --legacy-peer-deps

COPY frontend/ .

RUN npx vite build

FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
